version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - pgsql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - default
  pgsql:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      DB_HOST: pgsql
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homestead
      POSTGRES_PORT: 5432
    volumes:
      - ./postgres-data1:/var/lib/postgresql/data
    networks:
      - default
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - .:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:16
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - .:/var/www/html

networks:
  default:
    driver: bridge

volumes:
  postgres-data1: